name: hymnal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  google_fonts: ^6.3.2
  in_app_update: ^4.2.5
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
      - asset: assets/fonts/Lato-Italic.ttf
  - family: RobotoSlab
    fonts:
      - asset: assets/fonts/RobotoSlab-Regular.ttf
      - asset: assets/fonts/RobotoSlab-Bold.ttf
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Bold.ttf
      - asset: assets/fonts/Montserrat-Italic.ttf
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
      - asset: assets/fonts/OpenSans-Italic.ttf
  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather_120pt-Regular.ttf
      - asset: assets/fonts/Merriweather_120pt-Black.ttf
      - asset: assets/fonts/Merriweather_120pt-Italic.ttf
  assets:
    - assets/images/
    - assets/screenshots/
